### ISSUE TITLE
https://thenewobjective.com/a-criticism-of-web-components/

### ISSUE THREAD

**Issue by mlhaufe** [thenewobjective/thenewobjective.github.io#1]
Comment thread for <https://thenewobjective.com/a-criticism-of-web-components/>

**Comment by mlhaufe** [comment]
Updated June 10, 2019 with a link to [adambsilver‘s](https://twitter.com/adambsilver) related article.

**Comment by mlhaufe** [comment]
Updated April 29, 2019 with feedback from [@check_ca](https://twitter.com/check_ca/status/1121438171542228992)

**Comment by mlhaufe** [comment]
Updated August 21, 2018 with feedback from [adamdbradley](https://twitter.com/adamdbradley/status/1032026296916889600)

**Comment by javadmoradii** [comment]
- you cannot write unity or e2e test

**Comment by mlhaufe** [comment]
Some positive news on the standards and webkit fronts:

https://webkit.org/blog/13711/elementinternals-and-form-associated-custom-elements/

**Comment by mlhaufe** [comment]
A feature called Declarative Shadow DOM has been introduced:

https://webkit.org/blog/13851/declarative-shadow-dom/
